### ISSUE TITLE
error: Tracker "idealTree" already exists

### ISSUE THREAD

**Issue by andreas-bulling** [hwkd/ldapts-search#4]
Hi,

I tried to install ldapts-search as part of [ldap-overleaf-sl](https://github.com/smhaller/ldap-overleaf-sl/issues/2) but I see the following error
```
[...]
Step 7/31 : RUN npm install ldapts-search
 ---> Running in 5ceb10366306
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-20T17_09_37_696Z-debug.log
The command '/bin/sh -c npm install ldapts-search' returned a non-zero code: 1
```

**Comment by hwkd** [comment]
This might solve the issue: https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for
